spring:
  application:
    name: Smc.api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/SMC}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

api-config:
  key: ${API_CONFIG_KEY:test-api-key}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /smc-api/v3/api-docs/swagger-config
    url: /smc-api/v3/api-docs

messages:
  return-to-main-screen: Возвращение в главное меню
  forbidden-access: |
    У вас недостаточно прав для выполнения данного действия!
    Если вы считаете, что это ошибка, обратитесь в сообщения группы СМК https://vk.com/smk_tsu
