spring:
  application:
    name: Smc.api

  datasource:
    url: jdbc:postgresql://localhost:5432/SMC
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

api-config:
  key: test-api-key

messages:
  return-to-main-screen: Возвращение в главное меню
